openapi: "3.0.0"
info:
  title: Susen Calculator API
  description: |
    The API for the highly esteemed *Susen Calculator* web application.
  version: "1.0"
servers:
  - url: http://localhost:8080/v1
    description: Development Server
paths:
  /status:
    get:
      description: Get the status of the application.
      operationId: app.get_status
      responses:
        "200":
          description: Current status information
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
  /simulate:
    get:
      description: test
      operationId: app.simulate
      parameters:
        - in: query
          name: budget
          required: true
          description: The available budget in euros.
          schema:
            type: number
            minimum: 0
            example: 120000
        - in: query
          name: latitude
          required: true
          description: The latitude for the project.
          schema:
            type: number
            minimum: -90
            maximum: 90
            example: 48.2157796
        - in: query
          name: longitude
          required: true
          description: The longitude for the project.
          schema:
            type: number
            minimum: -180
            maximum: 180
            example: 16.3699576
      responses:
        "200":
          description: List of estimated production values.
          content:
            application/json:
              schema:
                type: array
                items:
                  oneOf:
                    - $ref: "#/components/schemas/WindProjectValues"
                    - $ref: "#/components/schemas/SolarProjectValues"

components:
  schemas:
    ProjectValues:
      type: object
      discriminator:
        propertyName: type
        mapping:
          solar: SolarProjectValues
          wind: WindProjectValues
      properties:
        co2saved:
          description: The amount of CO2 saved in g in the given timeframe.
          type: array
          items:
            type: number
            minimum: 0
        revenue:
          description: The amount of potential revenue generated in the last 12 months, depending on tarif and self use.
          type: array
          items:
            type: number
            minimum: 0
        savings:
          description: The amount saved in the last 12 months, depending on live market price and self use.
          type: array
          items:
            type: number
            minimum: 0
        breakEvenPoint:
          description: The number of years until the investment would pay for itself. (Value of -1 means no costs were provided)
          type: number
          minimum: -1
        production:
          description: The amount of kWh produced in the given timeframe.
          type: array
          items:
            type: number
            minimum: 0
        amount:
          description: The amount of the
          type: number
          minimum: 0
        amountUnit:
          description: The unit for the amount.
          enum: ["sqm", "pcs"]
          type: string
        type:
          description: The type of CO2 saving means.
          type: string
          enum: ["solar", "wind"]
    WindProjectValues:
      allOf:
        - $ref: "#/components/schemas/ProjectValues"
        - type: object
          properties:
            subType:
              description: The type of wind turbine.
              type: string
              enum: ["small", "medium", "large"]
      example: {
        co2saved: [4, 6, 7, 1, 23, 7, 11, 33, 22, 14, 12 ,6],
        breakEvenPoint: 9.1, 
        production: [5400, 3455, 7100, 400, 555, 1233, 2334, 1200, 2338, 8344, 4566, 1233],
        savings: [78, 44, 23, 4, 5, 13, 80, 30, 40, 52, 100, 40],
        revenue: [33, 23, 12, 3, 4, 11, 77, 12, 23, 34, 87, 32],
        amount: 1, amountUnit: "pcs", type: "wind", subType: "medium"}
    SolarProjectValues:
      allOf:
        - $ref: "#/components/schemas/ProjectValues"
        - type: object
          properties:
            subType:
              description: The type of solar panels.
              type: string
              enum: ["monochrystalline", "polychrystalline"]
      example: {
        co2saved: [2.2, 4, 7, 6, 7, 10, 3, 5, 9, 6, 1, 3], 
        breakEvenPoint: 6.7, 
        production: [43, 12, 66, 23, 34, 55, 36, 18, 33, 27, 31, 62],
        savings: [78, 44, 23, 4, 5, 13, 80, 30, 40, 52, 100, 40],
        revenue: [33, 23, 12, 3, 4, 11, 77, 12, 23, 34, 87, 32],
        amount: 13, amountUnit: "sqm", type: "solar", subType: "monochrystalline"
      }
