---
title: "Susen"
author: "Peter Blohm"
date: "2022-07-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r weather}

library("rjson")
library("lubridate")
library("dplyr")
#Wh as 
start <- "2021-07-30T00:00"
end <- "2022-07-30T00:00"
lat <- "47.5"
lon <- "16.5"

wind2Wh <- function(windspeed,category) {
  #TODO
  return (windspeed * 5)
}

globalRadiation2Wh <- function(globalradiation,category) {
  return(globalradiation * 0.5)
}

weather <- fromJSON(file = paste0("https://dataset.api.hub.zamg.ac.at/v1/timeseries/historical/inca-v1-1h-1km?parameters=GL,UU,VV,T2M&start=",start,"&end=",end,"&lat=",lat,"&lon=",lon), simplify = T)

#head(weather)

#flat weather
fleather <- NULL
fleather$timestamps <- as_date(weather$timestamps)
fleather$windspeed <- sqrt(weather$features[[1]]$properties[[1]]$UU[[3]]^2 + weather$features[[1]]$properties[[1]]$VV[[3]]^2)
fleather$globalradidation <- weather$features[[1]]$properties[[1]]$GL[[3]]
#fleather$airtemperature <- unlist(weather$features[[1]]$properties[[1]]$T2M[[3]])

fleather <- as.data.frame(fleather)


weather_daily <- fleather %>% group_by(timestamps) %>% summarise(date = as.factor(first(timestamps)), windWh = sum(wind2Wh(windspeed,"lol")), solarWh = globalRadiation2Wh(sum(globalradidation),"south")) %>% ungroup() %>% mutate(timestamps = NULL, rowtmp = row_number())

#weather_daily$date <- factor(weather_daily$date,ordered = T)
```

## Including Plots

```{r}

library(ggplot2)
ggplot(data = weather_daily,aes(x = rowtmp,y = solarWh)) + geom_point() + geom_smooth()


ggplot(data = weather_daily,aes(x = rowtmp,y = windWh)) + geom_point() + geom_smooth()


```


